# Step 1: Use an official Python runtime as a parent image
FROM python:3.9-slim

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy the requirements.txt file into the container
COPY requirements.txt .

# Step 4: Install the dependencies listed in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Step 5: Copy the rest of the application code into the container
COPY . .

# Step 6: Set the environment variable to avoid Python bytecode generation
ENV PYTHONUNBUFFERED 1

# Step 7: Expose the port your application will run on (if needed)
EXPOSE 5000

# Step 8: Define the command to run your application (for example, using Flask)
CMD ["python", "app.py"]
